### ISSUE TITLE
why does the location error drop dramatically at the first few frames?

### ISSUE THREAD

**Issue by cbtogu** [PRBonn/overlap_localization#1]
Hi, thanks for your great work!
I just look at the localization result gif you provide, the location error drops dramatically from more than 4 to a fairly low number at the first few frames, while the heading error stays at a normal level, what happened during this period?
Thank you.

**Comment by Chen-Xieyuanli** [comment]
Hey @cbtogu,

Thanks for following our work. 

During the initialization period. we uniformly generate the particles on the road and use the top 80% percent of the particles to estimate the pose. Therefore, before convergence, the pose estimations are highly dependent on the weighted average pose of the initialization, which will change for different runs or start points. 

After convergence, the pose estimation will keep around 0.3 meters and 3 degrees.

I hope my answer helps!

**Comment by cbtogu** [comment]
Thanks for your answer. @Chen-Xieyuanli 
So overlap is used for localizing consecutive lidar scans, not for just one scan, because it needs some scans for convergence, am I right?

**Comment by Chen-Xieyuanli** [comment]
Yes, it's a typical Bayesian process, where we iteratively estimate the pose posterior using consecutive observation and in the end converge to the correct one.

**Comment by cbtogu** [comment]
Thank you for your reply @Chen-Xieyuanli 
Another question, I try to verify the overlapnet localization using my own data, which is obtained in a big room. I want to use overlapnet for indoor localization with lidar scans.  We scan the room at a very slow speed (~0.1m/s or less), then we build a pcd point cloud manually, which is used to generate feature volumes for verification( we do NOT retrain the overlapnet) . But the localization result is very poor, not even close. So my question is:
1) Do I have to train the overlapnet for new weights use my own data ?
2) Which settings should I pay attetion to?
Thank you.

**Comment by Chen-Xieyuanli** [comment]
Hey @cbtogu,

1. We haven't tested our model with different scanners and environments so far, and I would also guess the pre-trained model will not perform well in totally different environments with different types of LiDAR scanners. However, for the localization problem, since you will anyway have the map beforehand, you could always train a new model for that map and it may work better.

2. For training a new model you could find a demo here: https://github.com/PRBonn/overlap_localization/blob/master/src/prepare_training/README.md

I hope this helps!

**Comment by cbtogu** [comment]
Thank you @Chen-Xieyuanli
