### ISSUE TITLE
.bin scan files in scan folder are different from KITTI dataset

### ISSUE THREAD

**Issue by kxhit** [PRBonn/overlap_localization#2]
Hi @Chen-Xieyuanli  Thanks a lot for your open-sourced code!

I found some minor difference between the .bin scan files from your compressed zip file and the original KITTI odometry dataset scans. I'm opening this issue for just letting you know and check. 

![图片](https://user-images.githubusercontent.com/16812362/103537005-80703980-4ece-11eb-9d59-b715dd276acb.png)

Happy New Year! 

Best,
XIn

**Comment by Chen-Xieyuanli** [comment]
Haha, I'm super happy to hear from you again my friend @kxhit and happy new year!

Yes, those are the postprocessed data using the semantic kitti to remove dynamics.
It's also a trick to avoid copyright issue, since I don't think we can directly release the raw dataset ;-).

I hope you all the best and have a great time in München!

**Comment by kxhit** [comment]
@Chen-Xieyuanli Thanks my friend! Good luck!
